version: '3.8'

services:
  app-service-test:
    build: .
    ports:
      - "3000:3000"
    environment:
      - FASTIFY_API_URL=http://db-service-test:8000
    depends_on:
      db-service-test:
        condition: service_healthy  # This ensures app-service waits for db-service to be healthy
    networks:
      - app-test-network
    command: yarn test  # Run tests inside the app-service

  db-service-test:
    build: ./db-service
    ports:
      - "8000:8000"
    env_file:
      - ./db-service/.env
    networks:
      - app-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-test-network:
    driver: bridge
